<?php /* Smarty version 2.6.26, created on 2012-08-12 09:34:32
         compiled from email_template:75 */ ?>
<?php if ($this->_tpl_vars['type'] == 1): ?> Dear <?php echo $this->_tpl_vars['task_owner']; ?>
, <BR><BR>This message is friendly reminder that the Task "<?php echo $this->_tpl_vars['task_url']; ?>
"<?php if ($this->_tpl_vars['notice_status'] == 9999): ?> has reached its completion date and time. This means that the completed date and time agreed upon when the task was awarded has passed. <?php else: ?> is due to be completed in less than <?php endif; ?><?php if ($this->_tpl_vars['notice_status'] == 172800): ?> two days! <?php endif; ?> <?php if ($this->_tpl_vars['notice_status'] == 86400): ?> 1 day! <?php endif; ?> <?php if ($this->_tpl_vars['notice_status'] == 10800): ?> 3 hours! <?php endif; ?> <?php if ($this->_tpl_vars['notice_status'] == 3600): ?> 1 hour! <?php endif; ?>&nbsp; (<?php echo $this->_tpl_vars['task_end']; ?>
) <?php if ($this->_tpl_vars['notice_status'] == 9999): ?>Please contact the Tasker as soon as possible to make arrangements to get the task completed. If both parties have agreed on additional time to complete the task you can disregard this notice. Please note it is at your discretion to file a dispute and have escrow payments canceled should Task Sonic Administration find the Tasker in default of meeting the agreed upon completion date and time.&nbsp; While we discourage doing so, it is your option on time sensitive tasks. Please see Task Sonic terms and conditions for more details on the dispute process<?php endif; ?><BR><BR>Please be certain to stay in contact with the Tasker <?php echo $this->_tpl_vars['tasker']; ?>
 to ascertain they are on track. You may receive additional reminders up until the task completion date has expired. The task will remain in the awarded state until the Tasker marks it completed, at which time you will need to release escrow payments in order to officially move the status of the Task to completed. <?php endif; ?> <?php if ($this->_tpl_vars['type'] == 2): ?> Dear <?php echo $this->_tpl_vars['tasker']; ?>
, <BR><BR>This message is a friendly reminder that the Task "<?php echo $this->_tpl_vars['task_url']; ?>
"<?php if ($this->_tpl_vars['notice_status'] == 9999): ?>has reached its completion date and time. This means that the completed date and time agreed upon when the task was awarded has passed. <?php else: ?> is due to be completed in less than <?php endif; ?><?php if ($this->_tpl_vars['notice_status'] == 172800): ?> two days! <?php endif; ?> <?php if ($this->_tpl_vars['notice_status'] == 86400): ?> 1 day! <?php endif; ?> <?php if ($this->_tpl_vars['notice_status'] == 10800): ?> 3 hours! <?php endif; ?> <?php if ($this->_tpl_vars['notice_status'] == 3600): ?> 1 hour! <?php endif; ?> (<?php echo $this->_tpl_vars['task_end']; ?>
) <?php if ($this->_tpl_vars['notice_status'] == 9999): ?>Please contact the Task Owner as soon as possible to make arrangements to get the task completed. Please note it is at the Task Owners discretion to file a dispute and have escrow payments canceled should we find the Tasker in default of meeting the agreed upon completion date and time. Please see Task Sonic terms and conditions for more details on the dispute process<?php endif; ?><BR><BR>Please be certain to stay in contact with the Task Owner <?php echo $this->_tpl_vars['task_owner']; ?>
 to ascertain they know where you are in the completion process. You may receive additional reminders up until the task completion date has expired. The task will remain in the awarded state until you mark it completed, at which time the Task Owner <?php echo $this->_tpl_vars['task_owner']; ?>
 will need to release escrow payments in order to officially move the status of the Task to completed. <?php endif; ?>